### ISSUE TITLE
/v1/verify - "stack":"Error: _email is not allowed

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-server#221]
Hey @seanmonstar, do you know what may cause this error:

```
fxa-oauth-server.db.VERBOSE: proxied {"method":"getToken","ret":{"clientId":[36,189,191,164,92,211,0,197],"userId":[4,146,181,201,19,231,79,215,152,24,94,147,3,100,60,35],"email":"vlad@mozilla.com","scope":["profile","oauth"],"createdAt":"2015-02-19T07:41:02.786Z","type":"bearer","token":[22,20,100,232,130,86,9,176,69,98,45,235,39,185,95,173,250,147,171,156,121,246,198,67,120,51,155,31,171,155,66,54]}}
fxa-oauth-server.server.hapi.CRITICAL: error.uncaught {"tags":["hapi","internal","implementation","error"],"error":{"isBoom":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}},"isDeveloperError":true}}
fxa-oauth-server.summary.ERROR: summary {"code":500,"errno":999,"method":"post","path":"/v1/verify","t":11,"auth":null,"payload":["token"],"stack":"Error: _email is not allowed\n    at Object.exports.create (/home/vladikoff/dev/fxa-local-dev/fxa-oauth-server/node_modules/hapi/node_modules/boom/lib/index.js:21:17)\n    at Object.exports.internal (/home/vladikoff/dev/fxa-local-dev/fxa-oauth-server/node_modules/hapi/node_modules/boom/lib/index.js:246:92)\n    at Object.exports.badImplementation (/home/vladikoff/dev/fxa-local-dev/fxa-oauth-server/node_modules/hapi/node_modules/boom/lib/index.js:282:23)\n    at postValidate (/home/vladikoff/dev/fxa-local-dev/fxa-oauth-server/node_modules/hapi/lib/validation.js:150:26)\n    at internals.Any._validateWithOptions (/home/vladikoff/dev/fxa-local-dev/fxa-oauth-server/node_modules/joi/lib/any.js:430:16)\n    at root.validate (/home/vladikoff/dev/fxa-local-dev/fxa-oauth-server/node_modules/joi/lib/index.js:102:23)\n    at exports.response (/home/vladikoff/dev/fxa-local-dev/fxa-oauth-server/node_modules/hapi/lib/validation.js:159:16)\n    at /home/vladikoff/dev/fxa-local-dev/fxa-oauth-server/node_modules/hapi/lib/request.js:304:13\n    at iterate (/home/vladikoff/dev/fxa-local-dev/fxa-oauth-server/node_modules/hapi/node_modules/items/lib/index.js:35:13)\n    at done (/home/vladikoff/dev/fxa-local-dev/fxa-oauth-server/node_modules/hapi/node_modules/items/lib/index.js:27:25)"}
```

I get this error when I try to use the fxa-oauth-console locally. I'm not clear where `_email is not allowed` is coming from. Did something chance in terms of validating users for the `oauth` scope?

**Comment by seanmonstar** [comment]
There's this line: https://github.com/mozilla/fxa-oauth-server/blob/master/lib/token.js#L30

It's tripping the response validation. I can't possibly remember why that line is there, though.

**Comment by rfk** [comment]
Was this resolved?  I seem to recall some chatter about it.

**Comment by vladikoff** [comment]
Fixed via https://github.com/mozilla/fxa-oauth-server/commit/92d4bfc30d5c9f17483f964195b8836bbb1e6557 Thanks for reminding to close this! :+1:
