### ISSUE TITLE
missing scope parameter causes a CRITICAL error to /v1/authorization

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-oauth-server#315]
Found while tracking down problems related to #314.

If I call POST /authorization w/o a `scope`, a critical error is logged:

> oauth-server PORT 9010-6 (out): fxa-oauth-server.server.hapi.CRITICAL: error.uncaught {"tags":["hapi","internal","implementation","error"],"error":{"isBoom":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}},"isDeveloperError":true}}
> oauth-server PORT 9010-6 (out): fxa-oauth-server.summary.ERROR: summary {"code":500,"errno":999,"method":"post","path":"/v1/authorization","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:42.0) Gecko/20100101 Firefox/42.0","t":8,"client_id":"98e6508e88680e1a","auth":null,"payload":["client_id","assertion","response_type","ttl","access_type","redirect_uri"],"stack":"Error: scope is not allowed to be empty\n    at Object.exports.create (/Users/stomlinson/development/fxa-local-dev/fxa-oauth-server/node_modules/hapi/node_modules/boom/lib/index.js:21:17)\n    at Object.exports.internal (/Users/stomlinson/development/fxa-local-dev/fxa-oauth-server/node_modules/hapi/node_modules/boom/lib/index.js:246:92)\n    at Object.exports.badImplementation (/Users/stomlinson/development/fxa-local-dev/fxa-oauth-server/node_modules/hapi/node_modules/boom/lib/index.js:282:23)\n    at postValidate (/Users/stomlinson/development/fxa-local-dev/fxa-oauth-server/node_modules/hapi/lib/validation.js:150:26)\n    at internals.Any._validateWithOptions (/Users/stomlinson/development/fxa-local-dev/fxa-oauth-server/node_modules/joi/lib/any.js:429:16)\n    at root.validate (/Users/stomlinson/development/fxa-local-dev/fxa-oauth-server/node_modules/joi/lib/index.js:102:23)\n    at exports.response (/Users/stomlinson/development/fxa-local-dev/fxa-oauth-server/node_modules/hapi/lib/validation.js:159:16)\n    at /Users/stomlinson/development/fxa-local-dev/fxa-oauth-server/node_modules/hapi/lib/request.js:304:13\n    at iterate (/Users/stomlinson/development/fxa-local-dev/fxa-oauth-server/node_modules/hapi/node_modules/items/lib/index.js:35:13)\n    at done (/Users/stomlinson/development/fxa-local-dev/fxa-oauth-server/node_modules/hapi/node_modules/items/lib/index.js:27:25)\n    at /Users/stomlinson/development/fxa-local-dev/fxa-oauth-server/node_modules/hapi/node_modules/hoek/lib/index.js:756:22\n    at process._tickDomainCallback (node.js:463:13)"}

The request body:
```json
{
  "client_id": "98e6508e88680e1a",
  "assertion":...,
  "response_type":"token"
}
```

The response body:
```json
{
  "code": 500,
  "errno": 999,
  "error": "Internal Server Error",
  "message": "An internal server error occurred",
  "info": "https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#errors"
}
```

expected:
No nasty stack trace with a message about an uncaught error at a minimum, possibly a missing parameter error returned to the client similar to the auth server.

**Comment by shane-tomlinson** [comment]
ref mozilla/fxa-content-server#2830
