### ISSUE TITLE
"Table 'fxa_oauth.refreshTokens' doesn't exist" error on https://stable.dev.lcip.org/

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-server#342]
@crankycoder tried to use our new refresh tokens but it failed with error 500, here's a log from `stable`:

```
fxa-oauth-server.db.ERROR: generateRefreshToken Error: ER_NO_SUCH_TABLE: Table 'fxa_oauth.refreshTokens' doesn't exist
    at Query.Sequence._packetToError (/data/fxa-oauth-server/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/data/fxa-oauth-server/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/data/fxa-oauth-server/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/data/fxa-oauth-server/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/data/fxa-oauth-server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/data/fxa-oauth-server/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
    --------------------
    at Pool.query (/data/fxa-oauth-server/node_modules/mysql/lib/Pool.js:180:23)
    at /data/fxa-oauth-server/lib/db/mysql/index.js:492:18
    at tryCatcher (/data/fxa-oauth-server/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/data/fxa-oauth-server/node_modules/bluebird/js/main/promise.js:427:31)
    at new Promise (/data/fxa-oauth-server/node_modules/bluebird/js/main/promise.js:53:37)
    at Object._query (/data/fxa-oauth-server/lib/db/mysql/index.js:491:12)
    at Object._write (/data/fxa-oauth-server/lib/db/mysql/index.js:460:17)
    at Object.generateRefreshToken (/data/fxa-oauth-server/lib/db/mysql/index.js:405:17)
    at /data/fxa-oauth-server/lib/db/index.js:145:41
    at tryCatcher (/data/fxa-oauth-server/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/data/fxa-oauth-server/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/data/fxa-oauth-server/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromiseAtPostResolution (/data/fxa-oauth-server/node_modules/bluebird/js/main/promise.js:224:10)
    at Promise.b (domain.js:183:18)
    at Async._drainQueue (/data/fxa-oauth-server/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/data/fxa-oauth-server/node_modules/bluebird/js/main/async.js:187:10)
    at Async.drainQueues (/data/fxa-oauth-server/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickDomainCallback (node.js:492:13)
```

**Comment by shane-tomlinson** [comment]
@jrgm - do we have to kick the server? @vladikoff suspects SQL update might need to be applied to add a missing table.

**Comment by rfk** [comment]
Weird.  The db claims to be at patch-level 10, which is the current max.  It has the other changes that were applied in the refresh-tokens patch [1], like an "offline" column on the "codes" table.  But it doesn't contain the "refreshTokens" table.

I'm going to create it by hand.

[1] https://github.com/mozilla/fxa-oauth-server/blob/master/lib/db/mysql/patches/patch-005-006.sql

**Comment by rfk** [comment]
mysql> show tables;
+---------------------+
| Tables_in_fxa_oauth |
+---------------------+
| clientDevelopers    |
| clients             |
| codes               |
| dbMetadata          |
| developers          |
| refreshTokens       |
| tokens              |
+---------------------+
7 rows in set (0.00 sec)

mysql> describe refreshTokens;
+-----------+--------------+------+-----+-------------------+-------+
| Field     | Type         | Null | Key | Default           | Extra |
+-----------+--------------+------+-----+-------------------+-------+
| token     | binary(32)   | NO   | PRI | NULL              |       |
| clientId  | binary(8)    | NO   | MUL | NULL              |       |
| userId    | binary(16)   | NO   | MUL | NULL              |       |
| email     | varchar(256) | NO   |     | NULL              |       |
| scope     | varchar(256) | NO   |     | NULL              |       |
| createdAt | timestamp    | NO   |     | CURRENT_TIMESTAMP |       |
+-----------+--------------+------+-----+-------------------+-------+
6 rows in set (0.04 sec)

mysql>

**Comment by rfk** [comment]
By contrast, latest.dev.lcip.org appears to have this table properly, so not sure what went wrong on stable.  Anyways, closing this out.
