### ISSUE TITLE
 accountEvent NetworkingError: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-server#343]
Seeing a spam of `Error: getaddrinfo ENOTFOUND` errors on the OAuth server. not sure what this at first glance, happening on https://stable.dev.lcip.org/

```
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
fxa-oauth-server.events.ERROR: accountEvent NetworkingError: getaddrinfo ENOTFOUND
```

**Comment by seanmonstar** [comment]
That log line is here: https://github.com/mozilla/fxa-oauth-server/blob/master/lib/events.js#L51

**Comment by seanmonstar** [comment]
Likely the value in `config.events.queueUrl` has a domain that doesn't resolve.

**Comment by rfk** [comment]
```
  "events": {
    "region": "antarctica-west-1",
    "queueUrl": "https://sqs.antarctica-west-1.amazonaws.com/142069644989/fxa-oauth-events"
  }
```

Yep.

**Comment by rfk** [comment]
I assume this would be fixed by https://github.com/mozilla/fxa-dev/issues/187

**Comment by seanmonstar** [comment]
@rfk yes it would. I'm going to close this, since the error is in the config, and not in this repo.
