### ISSUE TITLE
fxa-jwtool listed in devDependencies, used in lib/routes/token.js.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-oauth-server#345]
Ref https://github.com/mozilla/fxa-content-server/issues/3191.

I am seeing this error in our Travis logs:
```
fxa-oauth-server.CRITICAL: uncaughtException Error: Cannot find module 'fxa-jwtool'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/mozilla/fxa-content-server/node_modules/fxa-oauth-server/lib/routes/token.js:12:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/mozilla/fxa-content-server/node_modules/fxa-oauth-server/lib/routing.js:53:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

fxa-jwtool is used by lib/routes/token.js, but is listed as a devDependency and not part of npm-shrinkwrap.json.

**Comment by vladikoff** [comment]
Commit Ref https://github.com/mozilla/fxa-oauth-server/commit/0a0e3034bbcfedc7fddff7b8a5d333150a60566a

**Comment by shane-tomlinson** [comment]
When I add fxa-jwtools to the `dependencies` list and run `npm shrinkwrap`, I receive the the following error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/stomlinson/development/nvm/v0.10.40/bin/npm',
1 verbose cli   'shrinkwrap' ]
2 info using npm@2.14.0
3 info using node@v0.10.40
4 verbose stack Error: Problems were encountered
4 verbose stack Please correct and try again.
4 verbose stack invalid: esprima@1.1.0-dev /Users/stomlinson/development/fxa-oauth-server/node_modules/blanket/node_modules/falafel/node_modules/esprima
4 verbose stack     at shrinkwrap_ (/Users/stomlinson/development/nvm/v0.10.40/lib/node_modules/npm/lib/shrinkwrap.js:37:15)
4 verbose stack     at /Users/stomlinson/development/nvm/v0.10.40/lib/node_modules/npm/lib/shrinkwrap.js:31:5
4 verbose stack     at /Users/stomlinson/development/nvm/v0.10.40/lib/node_modules/npm/lib/ls.js:47:30
4 verbose stack     at /Users/stomlinson/development/nvm/v0.10.40/lib/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
4 verbose stack     at /Users/stomlinson/development/nvm/v0.10.40/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
4 verbose stack     at cb (/Users/stomlinson/development/nvm/v0.10.40/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /Users/stomlinson/development/nvm/v0.10.40/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
4 verbose stack     at cb (/Users/stomlinson/development/nvm/v0.10.40/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /Users/stomlinson/development/nvm/v0.10.40/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
4 verbose stack     at cb (/Users/stomlinson/development/nvm/v0.10.40/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
5 verbose cwd /Users/stomlinson/development/fxa-oauth-server
6 error Darwin 14.5.0
7 error argv "node" "/Users/stomlinson/development/nvm/v0.10.40/bin/npm" "shrinkwrap"
8 error node v0.10.40
9 error npm  v2.14.0
10 error Problems were encountered
10 error Please correct and try again.
10 error invalid: esprima@1.1.0-dev /Users/stomlinson/development/fxa-oauth-server/node_modules/blanket/node_modules/falafel/node_modules/esprima
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```
