### ISSUE TITLE
_initialClients() does not resolve if clients config is empty.

### ISSUE THREAD

**Issue by rhalff** [mozilla/fxa-oauth-server#386]
[_initialClients()](https://github.com/mozilla/fxa-oauth-server/blob/master/lib/db/index.js#L188) will not resolve if the [`clients`](https://github.com/mozilla/fxa-oauth-server/blob/master/lib/config.js#L41) configuration array is empty or not set.

Both [preClients](https://github.com/mozilla/fxa-oauth-server/blob/master/lib/db/index.js#L54) and [serviceClients](https://github.com/mozilla/fxa-oauth-server/blob/master/lib/db/index.js#L112) do not resolve nor reject the promise.

```bash
2016-02-03T15:44:38.922016294Z fxa-oauth-server.db.ERROR: ping TypeError: Cannot read property 'then' of undefined
2016-02-03T15:44:38.922062278Z     at exports._initialClients (/app/lib/db/index.js:188:22)
2016-02-03T15:44:38.922068070Z     at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23)
2016-02-03T15:44:38.922071941Z     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:507:31)
2016-02-03T15:44:38.922085739Z     at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:581:18)
2016-02-03T15:44:38.922089138Z     at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:697:14)
2016-02-03T15:44:38.922092826Z     at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:123:16)
2016-02-03T15:44:38.922096321Z     at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:133:10)
2016-02-03T15:44:38.922101493Z     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/main/async.js:15:14)
2016-02-03T15:44:38.922105021Z     at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by shane-tomlinson** [comment]
@seanmonstar - can you triage this as you see appropriate?

**Comment by vladikoff** [comment]
By default both values are `[]` (empty arrays). I don't think we can guard against all possible config values. If your not using clients/serviceClients just do not change the value. I'm guessing you forced it to be "empty". Let us know if we need to investigate this further.
