### ISSUE TITLE
Intermittent test failures with ER_DUP_FIELDNAME

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#400]
I thought these had stopped, but they're still happening:

https://travis-ci.org/mozilla/fxa-oauth-server/jobs/114582058
```
  2) should not insert already existing clients

fxa-oauth-server.db.mysql.ERROR: updateDbSchema Error: ER_DUP_FIELDNAME: Duplicate column name 'authAt'

    at Query.Sequence._packetToError (/home/travis/build/mozilla/fxa-oauth-server/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)

    at Query.ErrorPacket (/home/travis/build/mozilla/fxa-oauth-server/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)

    at Protocol._parsePacket (/home/travis/build/mozilla/fxa-oauth-server/node_modules/mysql/lib/protocol/Protocol.js:280:23)

    at Parser.write (/home/travis/build/mozilla/fxa-oauth-server/node_modules/mysql/lib/protocol/Parser.js:73:12)

    at Protocol.write (/home/travis/build/mozilla/fxa-oauth-server/node_modules/mysql/lib/protocol/Protocol.js:39:16)

    at Socket.<anonymous> (/home/travis/build/mozilla/fxa-oauth-server/node_modules/mysql/lib/Connection.js:96:28)

    at Socket.emit (events.js:95:17)

    at Socket.<anonymous> (_stream_readable.js:765:14)

    at Socket.emit (events.js:92:17)

    at emitReadable_ (_stream_readable.js:427:10)

    at emitReadable (_stream_readable.js:423:5)

    at readableAddChunk (_stream_readable.js:166:9)

    at Socket.Readable.push (_stream_readable.js:128:10)

    at TCP.onread (net.js:529:21)

    --------------------
```

**Comment by vladikoff** [comment]
I scanned some recent travis builds and haven't seen this error. We also dropped node 0.12 support and that is where we saw some build failures. @vbudhram or anyone else if you see `ER_DUP_FIELDNAME` again let's reopen this.
